meta_product_name: "Careview"
meta_title: "Careview - Find a carehome that fits your needs"
meta_description: "Careview shares real life experiences from residents of carehomes in your region. This helps you to make a better choice for your loved ones."
meta_image: "background2.jpg" # should exist in `app/assets/images/`
